name: 📦 Expo EAS Local Android Build

on:
  push:
    branches:
      - main  # run when pushing to main branch
  workflow_dispatch:  # allow manual trigger from GitHub

jobs:
  build-android-local:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v4

      - name: 🧱 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 🧰 Setup EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🧩 Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: 🔐 Decode custom keystore
        run: echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > my-release-key.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: 🏗️ Build Android AAB locally
        run: |
          eas build --platform android --profile production --local --non-interactive
        env:
          EAS_NO_VCS: 1
          EAS_LOCAL_BUILD_SKIP_CLEANUP: 1
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          ANDROID_KEYSTORE_PATH: my-release-key.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: 📤 Upload built AAB
        uses: actions/upload-artifact@v4
        with:
          name: expo-android-aab
          path: build/**/*.aab
